#!/usr/bin/env bash
# block all incoming traffic but allow ssh, http and https
sudo apt-get update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
sudo service ufw restart
